//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Domain.Business.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContextData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContextData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Payroll.Domain.Business.Tests.ContextData", typeof(ContextData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;ClientId&quot;:301190,&quot;ApplicableDiscount&quot;:10.0,&quot;NoOfPayPeriods&quot;:26,&quot;Employees&quot;:[{&quot;Id&quot;:&quot;57469f28-ce50-4978-8eb7-548f4ae7ae3f&quot;,&quot;EmployeeId&quot;:1001,&quot;ClientId&quot;:301190,&quot;FirstName&quot;:&quot;Arron&quot;,&quot;LastName&quot;:&quot;Admin&quot;,&quot;IsActive&quot;:true},{&quot;Id&quot;:&quot;25700e6b-5d64-41e2-9670-06d31bf338b6&quot;,&quot;EmployeeId&quot;:1002,&quot;ClientId&quot;:301190,&quot;FirstName&quot;:&quot;Emily&quot;,&quot;LastName&quot;:&quot;Employee&quot;,&quot;IsActive&quot;:true},{&quot;Id&quot;:&quot;606200aa-b1ea-4d86-802a-32a7c139bf97&quot;,&quot;EmployeeId&quot;:1003,&quot;ClientId&quot;:301190,&quot;FirstName&quot;:&quot;Darren&quot;,&quot;LastName&quot;:&quot;Employee&quot;,&quot;IsActive&quot;:true},{&quot;Id&quot;:&quot;8ec5e1e1- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DependentDeductionEngineInputContext {
            get {
                return ResourceManager.GetString("DependentDeductionEngineInputContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;ClientId&quot;:301190,&quot;ApplicableDiscount&quot;:10.0,&quot;NoOfPayPeriods&quot;:26,&quot;Employees&quot;:[{&quot;Id&quot;:&quot;57469f28-ce50-4978-8eb7-548f4ae7ae3f&quot;,&quot;EmployeeId&quot;:1001,&quot;ClientId&quot;:301190,&quot;FirstName&quot;:&quot;Arron&quot;,&quot;LastName&quot;:&quot;Admin&quot;,&quot;IsActive&quot;:true},{&quot;Id&quot;:&quot;25700e6b-5d64-41e2-9670-06d31bf338b6&quot;,&quot;EmployeeId&quot;:1002,&quot;ClientId&quot;:301190,&quot;FirstName&quot;:&quot;Emily&quot;,&quot;LastName&quot;:&quot;Employee&quot;,&quot;IsActive&quot;:true},{&quot;Id&quot;:&quot;606200aa-b1ea-4d86-802a-32a7c139bf97&quot;,&quot;EmployeeId&quot;:1003,&quot;ClientId&quot;:301190,&quot;FirstName&quot;:&quot;Darren&quot;,&quot;LastName&quot;:&quot;Employee&quot;,&quot;IsActive&quot;:true},{&quot;Id&quot;:&quot;8ec5e1e1- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmployeeDeductionEngineInputContext {
            get {
                return ResourceManager.GetString("EmployeeDeductionEngineInputContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;ClientId&quot;:301190,&quot;ApplicableDiscount&quot;:10.0,&quot;NoOfPayPeriods&quot;:26,&quot;Employees&quot;:[{&quot;Id&quot;:&quot;8ec5e1e1-0153-400c-8000-d976c98ab0f0&quot;,&quot;EmployeeId&quot;:1004,&quot;ClientId&quot;:301190,&quot;FirstName&quot;:&quot;AJ&quot;,&quot;LastName&quot;:&quot;Employee&quot;,&quot;IsActive&quot;:true}],&quot;BenefitPlans&quot;:[{&quot;Id&quot;:&quot;b14bd2ec-4131-4ab9-9b50-2fa738b3bef5&quot;,&quot;BenefitPlanProviderId&quot;:&quot;00000000-0000-0000-0000-000000000000&quot;,&quot;ClientId&quot;:301190,&quot;BenefitPlanName&quot;:&quot;United Health Care - PPO&quot;,&quot;BenefitDeductionCode&quot;:&quot;Health&quot;,&quot;EmployeeBenefitDeductionAmount&quot;:1000.0,&quot;DependentBenefitDeductionAmount&quot;:500 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmployeeDeductionIngineInputWithDiscount {
            get {
                return ResourceManager.GetString("EmployeeDeductionIngineInputWithDiscount", resourceCulture);
            }
        }
    }
}
